### ISSUE TITLE
Android File: fail readDirectory() errno=13

### ISSUE THREAD

**Issue by nitrag** [Topener/To.ImageCache#4] opened 2016-01-23 01:44 UTC
Same code, android return 0's

```
var blob = require('To.ImageCache').remoteImage(url);
Ti.API.info(JSON.stringify(blob));
var ratioX = maxWidth / blob.width; //hardcoded to imageView's max width since this is static to my needs, change for full functionality
var ratioY = maxWidth / blob.height;  //hardcoded for a square image for my needs, change to maxHeight for your needs
var ratio = Math.min(ratioX, ratioY);

var w = Math.round(blob.width * ratio);
var h = Math.round(blob.height * ratio);

Ti.API.info("w:"+ w + ", h:"+h);
```

log

```
//result for Android
[DEBUG] :  Module: Loading module: To.ImageCache -> Resources/To.ImageCache.js
[INFO] :   TIC - setting folder to ImgCache
[INFO] :   TIC - setting expireTime to 259200
[INFO] :   TIC - setting debug to false
[INFO] :   TIC - setting remoteBackup to false
[TRACE] :  Uploaded tiapp metadata with Appcelerator Platform!
[INFO] :   loading more...
[INFO] :   loading feed, fromUser = null
[DEBUG] :  Module: Loading module: alloy/controllers/utilities/feedTabs -> Resources/alloy/controllers/utilities/feedTabs.js
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
[INFO] :   Timeline: Timeline: Activity_launch_request id:com.eagledevelopers.offroad time:269039622
[INFO] :   New login successful, Nav is displayed
[DEBUG] :  SensorManager: registerListener :: 0, MPU6500 Acceleration Sensor, 200000, 0,
[DEBUG] :  Activity: performCreate Call secproduct feature valuefalse
[DEBUG] :  Activity: performCreate Call debug elastic valuetrue
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = app_name@79fcb8e
[INFO] :   Loaded preview, resizing...
[INFO] :   TIC - *************
[INFO] :   remote image
[INFO] :   8317ecaf58e0847e998abbabe0ac196e
[INFO] :   TIC - checking file in system - 8317ecaf58e0847e998abbabe0ac196e
[INFO] :   TIC - has file in system
[INFO] :   TIC - *************
[INFO] :   TIC - reading file from system 8317ecaf58e0847e998abbabe0ac196e
[INFO] :   TIC - checking file in system - 8317ecaf58e0847e998abbabe0ac196e
[ERROR] :  File: fail readDirectory() errno=13
[ERROR] :  File: fail readDirectory() errno=13
[ERROR] :  File: fail readDirectory() errno=20
[INFO] :   {"file":{"hidden":false,"nativePath":"file:///data/data/com.eagledevelopers.offroad/app_appdata/ImgCache/8317ecaf58e0847e998abbabe0ac196e","writable":true,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data/data/com.eagledevelopers.offroad/app_appdata/ImgCache","writable":true,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data/data/com.eagledevelopers.offroad/app_appdata","writable":true,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data/data/com.eagledevelopers.offroad","writable":true,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data/data","writable":false,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data","writable":false,"executable":false,"parent":{"hidden":false,"nativePath":"file:///","writable":false,"executable":false,"parent":null,"readonly":true,"directoryListing":["persdata","knox_data","sdcard","persist","preload","storage","efs","config","cache","acct","vendor","d","etc","tombstones","firmware-modem","firmware","mnt","ueventd.rc","ueventd.qcom.rc","system","sys","service_contexts","sepolicy_version","sepolicy","seapp_contexts","sbin","publiccert.pem","property_contexts","proc","init.zygote32.rc","init.usb.rc","init.trace.rc","init.target.rc","init.rilcarrier.rc","init.rc","init.qcom.usb.sh","init.qcom.usb.rc","init.qcom.syspart_fixup.sh","init.qcom.ssr.sh","init.qcom.sh","init.qcom.rc","init.qcom.factory.sh","init.qcom.early_boot.sh","init.qcom.class_core.sh","init.mdm.sh","init.environ.rc","init.container.rc","init.class_main.sh","init.carrier.rc","init","fstab.qcom","file_contexts","default.prop","data","root","dev"],"size":0,"apiName":"Ti.Proxy","name":"","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":[],"size":4096,"apiName":"Ti.Proxy","name":"data","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":[],"size":16384,"apiName":"Ti.Proxy","name":"data","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":["lib","cache","databases","files","shared_prefs","app_appdata","app_sslcache","app_Parse"],"size":4096,"apiName":"Ti.Proxy","name":"com.eagledevelopers.offroad","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":[".tilicense","trails.json","-161711023","-161711023-journal","FeedCache","-311829640.mbtiles","-311829640.mbtiles-journal","ImgCache"],"size":4096,"apiName":"Ti.Proxy","name":"app_appdata","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":["8317ecaf58e0847e998abbabe0ac196e","bf8f4df365b0350bab55450e96742567","afcd70c9fc9d3f0b21c134313598c185"],"size":4096,"apiName":"Ti.Proxy","name":"ImgCache","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":[],"size":537868,"apiName":"Ti.Proxy","name":"8317ecaf58e0847e998abbabe0ac196e","symbolicLink":false,"bubbleParent":true},"nativePath":"file:///data/data/com.eagledevelopers.offroad/app_appdata/ImgCache/8317ecaf58e0847e998abbabe0ac196e","height":0,"length":537868,"width":0,"mimeType":"application/octet-stream","apiName":"Ti.Blob","text":"����\u0000\u0010JFIF\u0000\u0001\u0001\u0000\u0000\u0001\u0000\u0001\u0000\u0000��\u0000C\u0000\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001��\u0000C\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001��\u0000\u0011\b\u00048\u0002�\u0003\u0001\"\u00
[INFO] :   0
[INFO] :   w:NaN, h:NaN

//result for iOS
[INFO] :   {}
[INFO] :   w:200, h:300
```

**Comment by nitrag** [comment] 2016-01-23 01:57
However it does work if I clear cache right after config....which defeats the purpose

```
require('To.ImageCache').config({
    debug: false, //default "false"
    expireTime: 259200, // time in seconds, default 43200 = 12 hours
    folder: 'ImgCache', // folder to store the cache in, default "ToCache"
    remoteBackup: false // iOS Only do you want the images to be backed up to iCloud?
});
require('To.ImageCache').clearCache();
```

log

```
[WARN] :   TiBlob: (KrollRuntimeThread) [1946,1946] getFile not supported for non-file blob types.
[WARN] :   TiBlob: (KrollRuntimeThread) [0,1946] getNativePath not supported for non-file blob types.
[INFO] :   {"file":null,"nativePath":null,"height":1080,"length":537868,"width":720,"mimeType":"image/bitmap","apiName":"Ti.Blob","text":null,"type":0,"bubbleParent":true}
[INFO] :   720
[INFO] :   w:227, h:340
```

**Comment by nitrag** [comment] 2016-01-23 05:14
Further troubleshooting reveals that even if I do the clearCache() function it works the first time, then if I go to another page in my app and return to the image cache page I will get the error again.

I'm assuming this is the error:

```
[ERROR] :  File: fail readDirectory() errno=13
[ERROR] :  File: fail readDirectory() errno=13
[ERROR] :  File: fail readDirectory() errno=20
```

**Comment by Topener** [comment] 2016-01-26 10:17
Thanks for this information. Sorry I haven't been very active here. Missed the notification(s). 

Does this also happen if you don't supply a folder name to the config but keep it default?

**Comment by nitrag** [comment] 2016-01-26 19:26
No dice, works once. Then I close controller, open different controller, reopen original and it fails for some reason. 

code

```
require('To.ImageCache').config({
    debug: true, //default "false"
    expireTime: 259200, // time in seconds, default 43200 = 12 hours
    //folder: 'ImgCache', // folder to store the cache in, default "ToCache"
    remoteBackup: false // iOS Only do you want the images to be backed up to iCloud?
});
//require('To.ImageCache').clearCache();


function resizeCacheKeepAspectRatio(url, maxWidth){
    Ti.API.info("Loaded preview, resizing...");
    var blob = require('To.ImageCache').remoteImage(url);
    Ti.API.info(JSON.stringify(blob));
    Ti.API.info(blob.width);
    var ratioX = maxWidth / blob.width; //hardcoded to imageView's max width since this is static to my needs, change for full functionality
    var ratioY = maxWidth / blob.height;  //hardcoded for a square image for my needs, change to maxHeight for your needs
    var ratio = Math.min(ratioX, ratioY);

    var w = Math.round(blob.width * ratio);
    var h = Math.round(blob.height * ratio);

    Ti.API.info("w:"+ w + ", h:"+h);
    return [require('ti.imagefactory').imageAsResized(blob, {width: 200, height: h, quality: 1}), w, h];
}
```

Full log showing working first time and fail second

```
[INFO] :   TIC - setting config
[INFO] :   TIC - setting expireTime to 259200
[INFO] :   TIC - setting debug to true
[INFO] :   TIC - setting remoteBackup to false
[INFO] :   loading more...
[INFO] :   loading feed, fromUser = null
[DEBUG] :  Module: Loading module: alloy/controllers/utilities/feedTabs -> Resources/alloy/controllers/utilities/feedTabs.js
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
[DEBUG] :  AbsListView: Get MotionRecognitionManager
[INFO] :   Loaded preview, resizing...
[INFO] :   TIC - *************
[INFO] :   remote image
[INFO] :   8317ecaf58e0847e998abbabe0ac196e
[INFO] :   TIC - checking file in system - 8317ecaf58e0847e998abbabe0ac196e
[INFO] :   TIC - doesn't have file yet
[INFO] :   Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
[INFO] :   I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
[TRACE] :  CustomViewBehind: behind INVISIBLE
[INFO] :   TIC - store file 8317ecaf58e0847e998abbabe0ac196e
[INFO] :   TIC - checking file in system - 8317ecaf58e0847e998abbabe0ac196e
[INFO] :   art: Background sticky concurrent mark sweep GC freed 28830(2MB) AllocSpace objects, 50(2MB) LOS objects, 7% free, 37MB/40MB, paused 772us total 189.886ms
[INFO] :   TIC - *************
[WARN] :   TiBlob: (KrollRuntimeThread) [23950,23950] getFile not supported for non-file blob types.
[INFO] :   {"file":null,"nativePath":null,"height":1080,"length":537868,"width":720,"mimeType":"image/bitmap","apiName":"Ti.Blob","text":null,"type":0,"bubbleParent":true}
[INFO] :   720
[WARN] :   TiBlob: (KrollRuntimeThread) [0,23950] getNativePath not supported for non-file blob types.
[INFO] :   w:227, h:340
[INFO] :   Loaded preview, resizing...
[INFO] :   TIC - *************
[INFO] :   remote image
[INFO] :   bf8f4df365b0350bab55450e96742567
[INFO] :   TIC - checking file in system - bf8f4df365b0350bab55450e96742567
[INFO] :   TIC - doesn't have file yet
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   art: Background partial concurrent mark sweep GC freed 11377(693KB) AllocSpace objects, 16(3MB) LOS objects, 28% free, 39MB/55MB, paused 1.127ms total 141.200ms
[INFO] :   TIC - store file bf8f4df365b0350bab55450e96742567
[INFO] :   TIC - checking file in system - bf8f4df365b0350bab55450e96742567
[INFO] :   TIC - *************
[WARN] :   TiBlob: (KrollRuntimeThread) [1799,25749] getFile not supported for non-file blob types.
[INFO] :   {"file":null,"nativePath":null,"height":720,"length":726633,"width":1080,"mimeType":"image/bitmap","apiName":"Ti.Blob","text":null,"type":0,"bubbleParent":true}
[INFO] :   1080
[INFO] :   w:340, h:227
[WARN] :   TiBlob: (KrollRuntimeThread) [0,25749] getNativePath not supported for non-file blob types.
[INFO] :   Loaded preview, resizing...
[INFO] :   TIC - *************
[INFO] :   remote image
[INFO] :   afcd70c9fc9d3f0b21c134313598c185
[INFO] :   TIC - checking file in system - afcd70c9fc9d3f0b21c134313598c185
[INFO] :   TIC - doesn't have file yet
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   TIC - store file afcd70c9fc9d3f0b21c134313598c185
[INFO] :   TIC - checking file in system - afcd70c9fc9d3f0b21c134313598c185
[INFO] :   TIC - *************
[WARN] :   TiBlob: (KrollRuntimeThread) [761,26510] getFile not supported for non-file blob types.
[WARN] :   TiBlob: (KrollRuntimeThread) [1,26511] getNativePath not supported for non-file blob types.
[INFO] :   {"file":null,"nativePath":null,"height":1080,"length":606858,"width":720,"mimeType":"image/bitmap","apiName":"Ti.Blob","text":null,"type":0,"bubbleParent":true}
[INFO] :   720
[INFO] :   w:227, h:340
[INFO] :   got 3 more...
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[DEBUG] :  HTTPClient: The persistent handle is disposed.
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] :  ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x1, toolType: 1
[INFO] :   loading more...
[INFO] :   loading feed, fromUser = null
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] :  ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x1, toolType: 1
[DEBUG] :  HTTPClient: The persistent handle is disposed.
[ERROR] :  libEGL: call to OpenGL ES API with no current context (logged once per thread)
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] :  ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x1, toolType: 1
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] :  ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x1, toolType: 1
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] :  ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x1, toolType: 1
[INFO] :   isLeftOpen: false
[DEBUG] :  ViewStack Count: 1
[INFO] :   toggle drawer window
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] :  ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x1, toolType: 1
[INFO] :   menu item clicked...
[INFO] :   Fetching new trail data
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
[INFO] :   art: Background sticky concurrent mark sweep GC freed 13079(912KB) AllocSpace objects, 48(11MB) LOS objects, 15% free, 43MB/51MB, paused 645us total 167.524ms
[DEBUG] :  AbsListView: Get MotionRecognitionManager
[INFO] :   Successfully received trail json: {"Colorado":{"Central":[{"ID":"H9vcRvXpkT","Name":"Mosquito Pass","Type":"Trail","difficulty":4,"distance":23875}],"Ouray":[{"ID":"QhJKowY0lz","Name":"Black Bear Pass ","Type":"Trail","difficulty":6,"distance":13710},{"ID":"1Esvfe3mUt","Name":"Imogene Pass","Type":"Trail","difficulty":6,"distance":27339}]},"Nevada":{"Southern":[{"ID":"lk77OFWk1N","Name":"Rainbow Garden and Lava Butte Loop","Type":"Trail","difficulty":1,"distance":27192},{"ID":"GdK0avpMBw","Name":"Burro Wash","Type":"Trail","difficulty":5,"distance":21159},{"ID":"CHmzJ9hwt9","Name":"Mormon Wells Road","Type":"Trail","difficulty":3},{"ID":"fj2OiewVdS","Name":"Gold Butte","Type":"Trail","difficulty":2,"distance":143888},{"ID":"yoL0IfeTQQ","Name":"Bitter Springs Back Country Byway","Type":"Trail","difficulty":2,"distance":75043},{"ID":"BURu4v8G6v","Name":"Titus Canyon","Type":"Trail","difficulty":3,"distance":42307}]},"Tennessee":{"Eastern":[{"ID":"31vN7vYwqp","Name":"Windrock ORV","Type":"Park"}]},"Utah":{"Central":[{"ID":"91yETOGoD0","Name":"Wild Horse Mesa ","Type":"Trail","difficulty":4,"distance":49047}],"Moab":[{"ID":"RoGaWwR5l6","Name":"White Rim","Type":"Trail","difficulty":5,"distance":111748}]}}
[INFO] :   Parsing trails into rows...
[INFO] :   Added: Colorado
[INFO] :   Added: Nevada
[INFO] :   Added: Tennessee
[INFO] :   Added: Utah
[DEBUG] :  HTTPClient: The persistent handle is disposed.
[INFO] :   APSAnalyticsService: Analytics Service Started
[ERROR] :  ViewRootImpl: sendUserActionEvent() mView == null
[INFO] :   I/System.out: Thread-26993(ApacheHTTPLog):Reading from variable values from setDefaultValuesToVariables
[TRACE] :  CustomViewBehind: behind INVISIBLE
[INFO] :   I/System.out: Thread-26993(ApacheHTTPLog):isShipBuild true
[INFO] :   I/System.out: Thread-26993(ApacheHTTPLog):SmartBonding Enabling is true, SHIP_BUILD is true, log to file is false, DBG is false
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] :  ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x1, toolType: 1
[INFO] :   isLeftOpen: false
[DEBUG] :  ViewStack Count: 1
[INFO] :   toggle drawer window
[INFO] :   I/System.out: Thread-26993 calls detatch()
[INFO] :   APSAnalyticsService: Stopping Analytics Service
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] :  ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
[INFO] :   I/InputDispatcher(  946): Delivering touch to : action: 0x1, toolType: 1
[INFO] :   menu item clicked...
[DEBUG] :  [nl.fokkezb.infiniteScroll] Do not forget to call init() passing a TableView or ListView
[DEBUG] :  Added PullToRefresh
[INFO] :   loading more...
[INFO] :   loading feed, fromUser = null
[INFO] :   I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO] :   I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
[DEBUG] :  AbsListView: Get MotionRecognitionManager
[INFO] :   Loaded preview, resizing...
[INFO] :   TIC - *************
[INFO] :   remote image
[INFO] :   8317ecaf58e0847e998abbabe0ac196e
[INFO] :   TIC - checking file in system - 8317ecaf58e0847e998abbabe0ac196e
[INFO] :   TIC - has file in system
[INFO] :   TIC - *************
[INFO] :   TIC - reading file from system 8317ecaf58e0847e998abbabe0ac196e
[INFO] :   TIC - checking file in system - 8317ecaf58e0847e998abbabe0ac196e
[ERROR] :  File: fail readDirectory() errno=13
[ERROR] :  File: fail readDirectory() errno=13
[ERROR] :  File: fail readDirectory() errno=20
[TRACE] :  CustomViewBehind: behind INVISIBLE
[INFO] :   {"file":{"hidden":false,"nativePath":"file:///data/data/com.eagledevelopers.offroad/app_appdata/ToCache/8317ecaf58e0847e998abbabe0ac196e","writable":true,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data/data/com.eagledevelopers.offroad/app_appdata/ToCache","writable":true,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data/data/com.eagledevelopers.offroad/app_appdata","writable":true,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data/data/com.eagledevelopers.offroad","writable":true,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data/data","writable":false,"executable":false,"parent":{"hidden":false,"nativePath":"file:///data","writable":false,"executable":false,"parent":{"hidden":false,"nativePath":"file:///","writable":false,"executable":false,"parent":null,"readonly":true,"directoryListing":["persdata","knox_data","sdcard","persist","preload","storage","efs","config","cache","acct","vendor","d","etc","tombstones","firmware-modem","firmware","mnt","ueventd.rc","ueventd.qcom.rc","system","sys","service_contexts","sepolicy_version","sepolicy","seapp_contexts","sbin","publiccert.pem","property_contexts","proc","init.zygote32.rc","init.usb.rc","init.trace.rc","init.target.rc","init.rilcarrier.rc","init.rc","init.qcom.usb.sh","init.qcom.usb.rc","init.qcom.syspart_fixup.sh","init.qcom.ssr.sh","init.qcom.sh","init.qcom.rc","init.qcom.factory.sh","init.qcom.early_boot.sh","init.qcom.class_core.sh","init.mdm.sh","init.environ.rc","init.container.rc","init.class_main.sh","init.carrier.rc","init","fstab.qcom","file_contexts","default.prop","data","root","dev"],"size":0,"apiName":"Ti.Proxy","name":"","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":[],"size":4096,"apiName":"Ti.Proxy","name":"data","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":[],"size":16384,"apiName":"Ti.Proxy","name":"data","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":["lib","cache","databases","app_sslcache","app_Parse","files","shared_prefs","app_appdata"],"size":4096,"apiName":"Ti.Proxy","name":"com.eagledevelopers.offroad","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":[".tilicense","trails.json","ToCache"],"size":4096,"apiName":"Ti.Proxy","name":"app_appdata","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":["8317ecaf58e0847e998abbabe0ac196e","bf8f4df365b0350bab55450e96742567","afcd70c9fc9d3f0b21c134313598c185"],"size":4096,"apiName":"Ti.Proxy","name":"ToCache","symbolicLink":false,"bubbleParent":true},"readonly":false,"directoryListing":[],"size":537868,"apiName":"Ti.Proxy","name":"8317ecaf58e0847e998abbabe0ac196e","symbolicLink":false,"bubbleParent":true},"nativePath":"file:///data/data/com.eagledevelopers.offroad/app_appdata/ToCache/8317ecaf58e0847e998abbabe0ac196e","height":0,"length":537868,"width":0,"mimeType":"application/octet-stream","apiName":"Ti.Blob","text":"����\u0000\u0010JFIF\u0000\u0001\u0001\u0000\u0000\u0001\u0000\u0001\u0000\u0000��\u0000C\u0000\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001��\u0000C\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001��\u0000\u0011\b\u00048\u0002�\u0003\u0001\"\u0000\u0002\u0011\u0001\u0003\u0011\u0001��\u0000\u001f\u0000\u0000\u0001\u0005\u0001\u0001\u0001\u0
[INFO] :   :  0
[INFO] :   w:NaN, h:NaN
```

**Comment by Topener** [comment] 2016-01-26 19:37
I never tested the module with a result of resizing an image. Only from camera/gallery or remote. Perhaps the response is not what it expects.... I will have to try and reproduce this issue.

Can you set up a minimum reproducible app? I will go and debug the issue from there

**Comment by nitrag** [comment] 2016-01-26 19:50
But I'm not storing the resized image am I? Just the original blob from the
URL...right?

**Comment by Topener** [comment] 2016-01-26 19:53
ah yes, you are correct, apologies. But my request remains, could you please provide a test-app so I can reproduce and fix :)

**Comment by nitrag** [comment] 2016-01-27 02:46
https://github.com/nitrag/ToImageCacheTest 

@Topener I hope it's not something stupid I'm doing...

**Comment by Topener** [comment] 2016-01-27 12:30
@nitrag thanks for this.
I installed it, installed `dk.napp.drawer` (which was missing, no worries). 

I wasn't able to reproduce in Genymotion. Neither with `5.1.1.GA` or `5.1.2.GA`. 

What Android SDK version do you use? You have 23 I presume?

**Comment by nitrag** [comment] 2016-01-27 19:04
I tested with Genymotion and still get the same error. Galaxy S5.

Did you uncomment line 37 of cached.js?

1) Open app, cached.js is initial controller.
2) Use the drawer and switch to "other page" (blank.js).
3) Use the drawer and switch back to "Cached Images" (cached.js)

You'll get an error on step 3. It works the first time around but not the second. 

Ti SDK 5.1.1GA. 

Thanks!

**Comment by Topener** [comment] 2016-01-27 19:17
Thanks @nitrag. I had forgotten to remove the comment. I also discovered the problem.

Because for the first time the file is returned, it will return a blob coming from an imageview `toBlob()` method.

The second time it returned the blob from a file. They behave differently... A fix for this problem is to replace the `remoteImage` function with the one at the bottom. This will always return the same object. (it should actually).

I would also recommend using the `cache()` method instead of the remote, as the UI will not be blocking while downloading it. However, that is up to you. 

I will publish an update later, and then close this issue. Thanks!

```
var remoteImage = function(url){
    if (c.debug){
        Ti.API.info('TIC - *************');
        Ti.API.info('remote image');
    }
    // calculate local filename
    var filename = md5FileName(url);
    Ti.API.info(filename);

    if (hasFile(filename)){
        if (c.debug){
            Ti.API.info('TIC - has file in system');
            Ti.API.info('TIC - *************');
        }

        var image = Ti.UI.createImageView({
            image : readFile(filename),
            width : Ti.UI.SIZE,
            height : Ti.UI.SIZE
        });

    } else {
        Ti.API.info('TIC - doesn\'t have file yet');

        // generate a blob
        var image = Ti.UI.createImageView({
            image : url,
            width : Ti.UI.SIZE,
            height : Ti.UI.SIZE
        });
    }
    var blob =  image.toBlob();
    image = null;

    storeFile(filename, blob);

    Ti.API.info('TIC - *************');
    return blob;
};
```

**Comment by nitrag** [comment] 2016-01-27 20:20
Awesome thanks!!!!!!

**Closed as completed** 2016-02-19 06:26 UTC
Labels: bug
